### ISSUE TITLE
可否交流一下  telegram+php

### ISSUE THREAD

**Issue by seiven** [PluginCloud/telegram#1]
可否交流一下  telegram+php

我想用PHP+telegram 客户端 + tdlib  搭建自己的即时聊天软件 , 不用搭梯子的那种, 
你有什么方法吗?

**Comment by tingfeng-key** [comment]
你可以看一下这两个库：

- [phptdlib](https://github.com/yaroslavche/phptdlib)

- [MadelineProto](https://github.com/danog/MadelineProto)

phptdlib是PHP的C++扩展，有一些简短的文档，需要熟悉telegram api。

MadelineProto是纯php实现的telegram客户端，最新版要求使用php7.4

**Comment by seiven** [comment]
非常感谢你的回复   

在我自己的服务器运行telegram api客户端后   可以用官方的客户端自己打包自己的IM是这样吗?  望指教

**Comment by seiven** [comment]
我可以加你好友吗?  wx qq 都可以  主要是不太清楚这个流程.  资料也挺少的

**Comment by tingfeng-key** [comment]
我不太明白你的意思，telegram api是官方提供给开发者用来创建客户端的接口

**Comment by seiven** [comment]
我想用telegram官方开源的Android 打包自己的IM  这个实现吗? 是通过telegram api+php 实现吗?
然后我根据telegram的用户标识什么的 做一些自己的业务
让通过我自己的这个IM 进来人使用我提供的一些服务

目标是借助telegram搭建一个自己的IM   然后再加上自己的特殊业务

**Comment by tingfeng-key** [comment]
1. telegram开源的android库已经实现了telegram api，你可以直接使用android库而不需要telegram api+php。
2. 我没有在telegram api做过类似你说的实现，但是理论上是可行的。

**Comment by seiven** [comment]
嗯 主要是要翻墙  这个问题比较费劲.   
所以如果用telegram搭建自己的IM(不用搭梯子的那种)  你有什么建议吗?

**Comment by tingfeng-key** [comment]
如果你主要喜欢telegram的加密，可以看一下官方中对于加密相关的文档，因为telegram本身是需要科学上网的。你也可以考虑下telegram服务器代理，关于telegram服务端代理已经有很多语言实现的第三方库，希望能帮到你。
